services:
  postgres:
    image: postgres:16-alpine
    container_name: planner-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PlannerDb
    volumes:
      - planner_postgres_data:/var/lib/postgresql/data
    
volumes:
  planner_postgres_data: